"""New2

Revision ID: 7b5d2336e0fc
Revises: c42d82c9ce43
Create Date: 2025-03-19 10:43:26.850384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b5d2336e0fc'
down_revision: Union[str, None] = 'c42d82c9ce43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels', sa.Column('namezz', sa.String(), nullable=False))
    op.drop_column('hotels', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('hotels', 'namezz')
    # ### end Alembic commands ###
